### ISSUE TITLE
-lua build option not needed

### ISSUE THREAD

**Issue by RCdiy** [GilDev/TaraniTunes#1]
Lua buil option is only to enable the custom scripts screen and run scripts in the scripts/mixes screen.
See
http://rcdiy.ca/opentx-guide/introduction-to-opentx-companion/#Transmitter_Profile_Build_Options
lua – Adds support for lua custom and mixes scripts. Support for other scripts such as telemetry scripts are always enabled

In 2.2.1 the wording in companion will be updated for more clarity.
https://github.com/opentx/opentx/pull/5277/files

**Comment by GilDev** [comment]
Thanks for the clarification!
