### ISSUE TITLE
Wavs stuck on repeat - how can I get single play mode

### ISSUE THREAD

**Issue by risben** [GilDev/TaraniTunes#16]
Hi there,

I've got this working, but as I'm using it as a sequence caller, I only want the wav to play once. I'm struggling to read the code well enough to find where the repeat is, or where I can place a break in play.

**Comment by jrwieland** [comment]
It can be used that way, however BGmusic was designed to play continuously, What you want it to do is play a track, to accomplish this change this line to make it more of a sequence caller (assuming the original file is in tact and you haven't deleted any lines).

Line 60 .......... func = 16 
to 
func = 11
