### ISSUE TITLE
Don´t work on OpenTx 2.3.5

### ISSUE THREAD

**Issue by VSemedo** [GilDev/TaraniTunes#17]
Hello,

I know that this tread is inactive from some time now, but i find it :)

I am trying to work whit that music player on my taranis qx7s and i can´t. I think everything is ok it play sounds normaly, in lua script the timer goes on but dont make any sound.

Thanks

**Comment by GilDev** [comment]
Hi,
There you go, fixed it just for you! 😃
Tested with the simulator on OpenTX 2.3.7, I think it will work with 2.3.5, please tell me if it does or doesn’t.

It seems @jrwieland’s [fork](https://github.com/jrwieland/TaraniTunes_v3.0.1) is working, although we don’t have the same offsets to set the special function’s switch, see mine:
```lua
if LCD_W == 212 then -- if Taranis X9D
	playSongSwitchId = 53 + playSongLogicalSwitch
else -- if Taranis Q X7
	playSongSwitchId = 44 + playSongLogicalSwitch
end
```

And the fork’s:
```lua
if LCD_W == 212 then -- if Taranis X9D
	playSongSwitchId = 50 + playSongLogicalSwitch
	model.setLogicalSwitch(58,{func=3,v1=230,v2=playlist[playingSong][3]})
elseif shPresent== 0 then -- if Taranis Xlite
	playSongSwitchId = 32 + playSongLogicalSwitch
	model.setLogicalSwitch(58,{func=3,v1=223,v2=playlist[playingSong][3]})
else 	playSongSwitchId = 38 + playSongLogicalSwitch-- if Taranis Q X7 
	model.setLogicalSwitch(58,{func=3,v1=225,v2=playlist[playingSong][3]})
end
```

Do you know why, @jrwieland?

**Comment by jrwieland** [comment]
Thanks for the heads up Too.  I'll check it out and see you c I have the
same issue.  Still running an older version on my transmitter.

John

**Comment by GilDev** [comment]
@jrwieland I’ve modified my message since, please check on GitHub when you have time, your version seems to work on the simulator but there is a difference in our codes and I’m not sure why.

**Comment by jrwieland** [comment]
I have added a few extra features. And it handles the music differently
than your original version.
But I'll check it out to make sure it is comparable with the latest version
of OpenTX.

**Comment by VSemedo** [comment]
thanks. I made it work a few hours ago. :)
