### ISSUE TITLE
File arrangements

### ISSUE THREAD

**Issue by RCdiy** [GilDev/TaraniTunes#2]
To make it easier for the user maybe have a new folder /MUSIC/ and have files put there by default. This way language won't matter and the /sounds/<language>/ folder is less cluttered.

**Comment by GilDev** [comment]
I thought about this but sadly you cannot create a “BgMusic” special function with a file in a different directory than `/SOUNDS/lang/`.
You cannot specify a path at all, just a filename of a file located in this folder.
