### ISSUE TITLE
Determining Radio Type

### ISSUE THREAD

**Issue by RCdiy** [GilDev/TaraniTunes#3]
Use LCD_W for radio type.
https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/lcd/lcd_functions-overview.html

If LCD_W < 212 then X7 series
else if > 212 then X10 series
else == 212, X9 series

**Comment by GilDev** [comment]
That's exactly how it's currently done. =)
But in regard of future radios that could come out, it would be cleaner to have constants to determine the radio type, or better, normalize logic switches' indexes.

**Comment by RCdiy** [comment]
Won't happen... memory limitations... they have to squueze every byte...

**Comment by GilDev** [comment]
Too bad… A constant to give the index of the first logical switch would be nice otherwise.
If they want to squeeze more, a C API to develop scripts would be quite cool!

**Comment by RCdiy** [comment]
Are you on the lua thread?
https://www.rcgroups.com/forums/showthread.php?2180477-LUA-scripting-Technical-discussion/page159

**Comment by GilDev** [comment]
Nope, didn't know about it. I'll take a look.

**Comment by RCdiy** [comment]
They are very helpful :)

**Comment by GilDev** [comment]
I'll go tell them about my thoughts and suggestions, thanks! =)
