### ISSUE TITLE
playlist.txt not correctly parsed if not using UNIX newlines

### ISSUE THREAD

**Issue by ralsei** [GilDev/TaraniTunes#4]
Once again, Windows proves to be a total pain in the ass.

I initially created my playlist using Notepad (vanilla) on Win10, and TaraniTunes would only play audio for the last item in the playlist. My playlist IS formatted correctly.

After converting to UNIX newlines, the problem is resolved.

I am using a Taranis X9D+ on OpenTX 2.2.0.

**Comment by ralsei** [comment]
The problem is likely at https://github.com/GilDev/TaraniTunes/blob/59365ba805c0b21478b03a1cc8cb1e0992acec76/iTunes.lua#L98.

I would fix it but I'm not booted into Linux (which has my text editor and git setup, unlike Windows), and I'm lazy as hell.

**Comment by GilDev** [comment]
Oh god, I hate Windows so much… Thanks for pointing that out though, it was an easy fix!
