### ISSUE TITLE
Script syntax error, not enough memory

### ISSUE THREAD

**Issue by Milu1980** [GilDev/TaraniTunes#8]
hi,

can somebody help me, why have i this massage?
playlist file was 10 times controlled, all ok.
the program starting 1s and go down, but the song will be played in the background.
i have just 6 songs, 16 bit mono, 32khz. 4GB SD card, 3,5GB free. Taranis X9d plus.
opentx 2.2.1 cca71808
thx .

**Comment by ChrisFpv** [comment]
I don't have time to explain it but i think Joshua can help you!!!!!!

https://www.youtube.com/watch?v=XAok49_MbkQ

**Comment by ChrisFpv** [comment]
I don't have time to explain it but i think Joshua can help you!!!!!
https://www.youtube.com/watch?v=1Ccz5gxAX2M

**Comment by GilDev** [comment]
That explains the concept but not why it is happening with TaraniTunes, internally speaking.
I don't know why it happens, but I know I should look into the code to optimize it, maybe remove that playlist.txt file which, although being practical, seems to cause problems with memory.
I personally have no trouble with OpenTX 2.2.1 on an X7 with ~30 songs.

**Comment by Milu1980** [comment]
Hi,

Can you please send me your program files ?
I try it...
Thx.
Milan

2018. febr. 26. 19:13 ezt írta ("GilDev" <notifications@github.com>):

That explains the concept but not why it is happening with TaraniTunes,
internally speaking.
I don't know why it happens, but I know I should look into the code to
optimize it, maybe remove that playlist.txt file which, although being
practical, seems to cause problems with memory.
I personally have no trouble with OpenTX 2.2.1 on an X7 with ~30 songs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GilDev/TaraniTunes/issues/8#issuecomment-368595532>,
or mute
the thread

**Comment by GilDev** [comment]
The example provided on this repo is working for me. See the "[Example](https://github.com/GilDev/TaraniTunes/tree/master/Example/SOUNDS)" folder.

**Comment by Milu1980** [comment]
hi,
i cant download it, can you please send me the lua, wav and the playlist
file ?
thx, very much.
Milan

2018-02-26 19:38 GMT+01:00 GilDev <notifications@github.com>:

**Comment by GilDev** [comment]
It's on the main page: https://github.com/GilDev/TaraniTunes/archive/master.zip

**Comment by Milu1980** [comment]
Hi,

AND WORKING :))))))))))
thx very much !

2018-02-26 21:42 GMT+01:00 GilDev <notifications@github.com>:

**Comment by GilDev** [comment]
Fixed in 4f39d45.

**Comment by Milu1980** [comment]
Hi,

it was too fast...
it runing, but dont play the music.
thx.

2018-02-26 23:00 GMT+01:00 GilDev <notifications@github.com>:
