### ISSUE TITLE
Working on Taranis x9d+ but playing just Music4

### ISSUE THREAD

**Issue by Milu1980** [GilDev/TaraniTunes#9]
Hi,

its playing just the file Music4, if i change the music playing too, but just Music4.
can you please help me?
thx.
![20180227_222840](https://user-images.githubusercontent.com/36828631/36756069-53395d8e-1c0e-11e8-8695-cbe6b741a442.jpg)
![20180227_222857](https://user-images.githubusercontent.com/36828631/36756070-53673b50-1c0e-11e8-9b0c-4ec9eeacae51.jpg)
![20180227_223030](https://user-images.githubusercontent.com/36828631/36756071-5396c6c2-1c0e-11e8-9f87-a3d3f49dabd1.jpg)

**Comment by GilDev** [comment]
That is weird. What version of OpenTX do you have?

**Comment by Milu1980** [comment]
4GB SD card, 3,8GB free. Taranis X9d plus.
opentx 2.2.1 cca71808

**Comment by GilDev** [comment]
Is your `playlist.lua` file correct? Be sure to use the latest version with `playlist.lua` and not `playlist.txt`. I published it yesterday so maybe you are not up to date. =)

**Comment by Milu1980** [comment]
I think, this is the problem... i have playlist.txt.
Have you a link to download it ?
Thx.

2018. febr. 27. 23:58 ezt írta ("GilDev" <notifications@github.com>):

**Comment by Milu1980** [comment]
Can i edit it like a txt ?

2018. febr. 28. 0:07 ezt írta ("Radics Milán" <radicsmilan@gmail.com>):

**Comment by GilDev** [comment]
The file is in the `Example` folder. Yes it is edited in a normal text editor like a .txt.

**Comment by Milu1980** [comment]
Hi,

It playing just music4...
Taranis x9d+

Maybe the problem is the Program version ?
Would be run with 2.2.0 ?
Thx.

**Comment by GilDev** [comment]
Well I don't know where the issue comes from. I myself run 2.2.1 and have no problems whatsoever…
All the files were copied without problems?

**Comment by Milu1980** [comment]
Can you please send me your files...
Maybe i have the worngs.
Thx.

**Comment by Milu1980** [comment]
Local playing song = 1
Local selection = 1


What is this in Itunes.lua ?

**Comment by GilDev** [comment]
Mine are the same that are available on the repo.

These are "cursors" that point to the current playing song and the current selected song respectively.

**Comment by Milu1980** [comment]
My Friend has a qx7s and there is the Itunes.lua 
Local playing song = 2
Local selection = 3

**Comment by GilDev** [comment]
Yes that is the old version of TaraniTunes.
If you use the new version with the `playlist.lua` file instead of the `playlist.txt` one, you will have
```
local playingSong = 1
local selection = 1
```

**Comment by Milu1980** [comment]
I am checking  the file, but i dont find the error...
Do you know, why playing this just Music4?
Thx.

2018. márc. 1. 20:02 ezt írta ("GilDev" <notifications@github.com>):

**Comment by GilDev** [comment]
Hey,
Sorry, have you been able to make TaraniTunes work with your radio?

**Comment by devosthomas** [comment]
I have the same issue. OpentX 2.2.2 - 9XD+ and your latest LUA script version.
I installed your latest github repo. Then I saw you have to create the playlist.lua file what I did. The player did nothing. I copied your playlist.lua over and the sample music files. It now worked but whatever selection I make it always plays music 3. Seems something is wrong.

**Comment by GilDev** [comment]
I’m sorry I don’t know from where this problem come as I can’t get to replicate it…

**Comment by jrwieland** [comment]
Gil I found the problem with devosthomas's situation he had tried installing a couple different music players including my version and had several Special functions all trying to play music (SF19, SF28, SF29 and SF30).  I helped him repair it.

**Comment by Milu1980** [comment]
Its ok, is working.

John Wieland <notifications@github.com> schrieb am So., 21. Okt. 2018,
23:21:

**Comment by GilDev** [comment]
Alright thanks for that, so it was a configuration problem. Maybe the instructions aren’t clear enough?
By the way, that is some impressive stuff you made on your [TaraniTunes fork](https://github.com/jrwieland/TaraniTunes-2.2), congratulations! I’m glad it’s useful to you and hopefully others!
